version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=your_database_name
      - DB_USER=your_database_user
      - DB_PASSWORD=your_database_password
    volumes:
      - ./backend:/backend
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
